CREATE TABLE "GAB_6538_FiscPeriod"(
 "PERIOD" CHAR(2),
 "BEG_DATE" CHAR(10),
 "END_DATE" CHAR(10),
 "LAST_DATE_CHG" CHAR(8),
 "LAST_USR_CHG" CHAR(50));

CREATE UNIQUE INDEX "GAB_6538_K00" ON "GAB_6538_FiscPeriod"("PERIOD");